import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { DataSource, EntityManager, In, IsNull, LessThan, LessThanOrEqual, MoreThan, Repository } from "typeorm";
import { buildIdempotencyKey, DomainAggregateType, DomainEventPublisher, DomainEventType, excerpt, MessageReceivedEvent } from "src/common/events";
import { User } from "src/modules/users/entities/user.entity";
import {
  AddParticipantsDto,
  ConversationPageResponseDto,
  ConversationQueryDto,
  ConversationResponseDto,
  CreateDirectConversationDto,
  CreateGroupConversationDto,
  DeliveryStateResponseDto,
  MessagePageResponseDto,
  MessageQueryDto,
  MessageResponseDto,
  ReadStateResponseDto,
  SendMessageDto,
  SendMessageResponseDto,
  UpdateConversationDto,
  UpdateDeliveryStateDto,
  UpdateReadStateDto
} from "./dto";
import { CONVERSATION_MAX_PARTICIPANTS, CONVERSATION_MODERATOR_ROLES, ConversationParticipantRole, ConversationType, MessageDeliveryState, MessageType } from "./enums";
import { Conversation, ConversationParticipant, Message, MessageReceipt } from "./entities";
import { MessagingRealtimeBus } from "./messaging-realtime.bus";

/** Upper bound on user ids resolved per display-name lookup. */
const NAME_BATCH_LIMIT = 200;

/**
 * Upper bound on receipt rows written by one state report.
 *
 * A first-ever "mark read" on a long thread would otherwise write one receipt
 * per message. The bound is a safety valve, not the normal path: reports are
 * bounded below by the caller's previous mark, so in steady state this writes
 * only what arrived since the last report.
 */
const RECEIPT_BATCH_LIMIT = 500;

/** Why an authorisation check failed. Never returned to the client verbatim. */
export type MessagingAccessError = "not_a_participant" | "not_a_moderator";

/**
 * A 404 that also carries a machine-readable reason for logs and WebSocket
 * error frames. Deliberately `NotFoundException` rather than `Forbidden` — see
 * the class comment on {@link MessagingService}.
 */
export class MessagingAccessException extends NotFoundException {
  constructor(readonly reason: MessagingAccessError) {
    super("Conversation not found");
  }
}

/**
 * MESSAGING SERVICE
 * ---------------------------------------------------------------------------
 * All conversation state, authorisation and message persistence lives here. The
 * WebSocket gateway is a thin transport shim over this class: it verifies the
 * token, then calls the very same methods the HTTP controller calls, so a frame
 * and a REST request can never diverge in what they are allowed to do.
 *
 * ─── The authorisation model ────────────────────────────────────────────────
 * An ACTIVE `conversation_participants` row (`left_at IS NULL`) is the *only*
 * thing that grants access. Every read, every write and every frame is gated on
 * one, and there is no second code path: `requireMembership` is the single
 * chokepoint and both transports funnel through it. Moderation — adding or
 * removing participants, renaming a thread — additionally requires an
 * OWNER/ADMIN role, because membership alone must not imply control.
 *
 * Non-members get **404, not 403**. A 403 would confirm the id exists, turning
 * the id space into an oracle for enumerating who is talking to whom. 404 for
 * both "no such conversation" and "not yours" is the only answer that leaks
 * nothing. This matches `CoachClientRelationshipService.loadOwnedBy`.
 *
 * ─── Why sends are transactional ────────────────────────────────────────────
 * `sendMessage` writes the message, the conversation-list projection, the
 * recipients' unread counters **and** the outbox row in one transaction. Two
 * things follow:
 *
 *   - A committed message always has its notification event, so "the athlete
 *     received the message but their coach was never told" is unreachable.
 *   - The transaction contains no provider I/O — `DomainEventPublisher` only
 *     INSERTs one row. That is what makes "a failed notification cannot fail the
 *     message transaction" true by construction rather than by discipline.
 *
 * The live WebSocket broadcast happens *after* the commit, never inside it, so a
 * subscriber can never see a message that later rolls back.
 *
 * ─── Idempotency, in two independent layers ────────────────────────────────
 *   1. `clientMessageId` — generated by the client, so a send retried over a
 *      flaky connection resolves to the original row. Unique on
 *      `(conversation, sender, clientMessageId)`; the loser of a race catches
 *      23505 and re-reads rather than failing the call.
 *   2. `directKey` — the sorted participant pair, unique, so "start a chat with
 *      X" can be issued any number of times and yields exactly one thread.
 */
@Injectable()
export class MessagingService {
  constructor(
    @InjectRepository(Conversation) private readonly conversationsRepo: Repository<Conversation>,
    @InjectRepository(ConversationParticipant) private readonly participantsRepo: Repository<ConversationParticipant>,
    @InjectRepository(Message) private readonly messagesRepo: Repository<Message>,
    @InjectRepository(MessageReceipt) private readonly receiptsRepo: Repository<MessageReceipt>,
    @InjectRepository(User) private readonly usersRepo: Repository<User>,
    private readonly dataSource: DataSource,
    private readonly eventPublisher: DomainEventPublisher,
    private readonly realtimeBus: MessagingRealtimeBus
  ) {}

  // ─── Authorisation ────────────────────────────────────────────────────────

  /**
   * The single authorisation chokepoint for the whole module.
   *
   * Returns the caller's active membership, which every caller needs anyway, so
   * authorisation costs no extra round-trip and cannot be forgotten at a call
   * site. Throws {@link MessagingAccessException} (a 404) for a non-member, a
   * member who has left, a soft-deleted membership, and for an id that does not
   * exist at all.
   */
  async requireMembership(userId: string, conversationId: string, manager?: EntityManager): Promise<ConversationParticipant> {
    const repo = manager ? manager.getRepository(ConversationParticipant) : this.participantsRepo;
    const participant = await repo.findOne({ where: { conversationId, userId, leftAt: IsNull(), isDeleted: false } });
    if (!participant) throw new MessagingAccessException("not_a_participant");
    return participant;
  }

  /**
   * Membership *plus* a moderator role.
   *
   * Split from `requireMembership` so the gateway can distinguish "not allowed
   * here" (403, and the socket is a legitimate member) from "not allowed
   * anywhere" (404), without a second lookup.
   */
  async requireModerator(userId: string, conversationId: string, manager?: EntityManager): Promise<ConversationParticipant> {
    const participant = await this.requireMembership(userId, conversationId, manager);
    if (!CONVERSATION_MODERATOR_ROLES.includes(participant.role)) throw new ForbiddenException("Only an owner or admin can perform this action");
    return participant;
  }

  /**
   * Every conversation the user is an active member of.
   *
   * The gateway calls this once per connection to compute the set of rooms that
   * socket may join. Precomputing the set is what makes "subscribe to a
   * conversation you are not in" structurally impossible rather than merely
   * rejected frame by frame.
   */
  async activeConversationIds(userId: string): Promise<string[]> {
    const rows = await this.participantsRepo.find({ where: { userId, leftAt: IsNull(), isDeleted: false }, select: { conversationId: true } });
    return rows.map((r) => r.conversationId);
  }

  // ─── Conversations ────────────────────────────────────────────────────────

  /**
   * Opens — or returns — the one-to-one thread with `participantId`.
   *
   * Idempotent by construction: the sorted participant pair is stored in a
   * uniquely indexed `direct_key`, so N concurrent calls produce exactly one
   * conversation. The insert is `ON CONFLICT DO NOTHING` followed by a re-read,
   * which is what makes this safe under a race without taking a lock.
   */
  async createDirectConversation(userId: string, dto: CreateDirectConversationDto): Promise<ConversationResponseDto> {
    if (dto.participantId === userId) throw new BadRequestException("You cannot start a conversation with yourself");

    const other = await this.usersRepo.findOne({ where: { id: dto.participantId, isDeleted: false }, select: { id: true } });
    if (!other) throw new NotFoundException("User not found");

    const directKey = buildDirectKey(userId, dto.participantId);
    const existing = await this.conversationsRepo.findOne({ where: { directKey, isDeleted: false } });
    if (existing) return this.getConversation(userId, existing.id);

    const conversationId = await this.dataSource.transaction(async (manager) => {
      const result = await manager
        .createQueryBuilder()
        .insert()
        .into(Conversation)
        .values({ type: ConversationType.DIRECT, title: null, createdById: userId, directKey })
        .orIgnore()
        .execute();

      // `raw` holds only the rows Postgres actually inserted. An empty result
      // means a concurrent request won the race — its participants already
      // exist, so there is nothing left to do.
      const row = Array.isArray(result.raw) ? (result.raw[0] as { id?: string } | undefined) : undefined;
      if (!row?.id) return null;

      await manager.save(
        ConversationParticipant,
        [userId, dto.participantId].map((participantUserId) =>
          manager.create(ConversationParticipant, {
            conversationId: row.id as string,
            userId: participantUserId,
            role: ConversationParticipantRole.MEMBER,
            isMuted: false,
            unreadCount: 0,
            readState: MessageDeliveryState.SENT,
            lastReadMessageId: null,
            lastReadAt: null,
            lastDeliveredMessageId: null,
            lastDeliveredAt: null,
            leftAt: null
          })
        )
      );
      return row.id;
    });

    // Whether we created it or a racer did, exactly one thread exists for the
    // pair — so resolving by key is always the right way to finish.
    const conversation = await this.conversationsRepo.findOneOrFail({ where: { directKey, isDeleted: false } });
    return this.getConversation(userId, conversationId ?? conversation.id);
  }

  /** Creates a group thread. The creator becomes OWNER. */
  async createGroupConversation(userId: string, dto: CreateGroupConversationDto): Promise<ConversationResponseDto> {
    const memberIds = [...new Set([userId, ...dto.participantIds])];
    if (memberIds.length > CONVERSATION_MAX_PARTICIPANTS) {
      throw new BadRequestException(`A conversation may have at most ${CONVERSATION_MAX_PARTICIPANTS} participants`);
    }

    const known = await this.usersRepo.find({ where: { id: In(memberIds), isDeleted: false }, select: { id: true } });
    if (known.length !== memberIds.length) throw new NotFoundException("One or more participants not found");

    const conversation = await this.conversationsRepo.save(
      this.conversationsRepo.create({ type: ConversationType.GROUP, title: dto.title.trim(), createdById: userId, directKey: null })
    );

    await this.participantsRepo.save(
      memberIds.map((memberId) => this.newParticipant(conversation.id, memberId, memberId === userId ? ConversationParticipantRole.OWNER : ConversationParticipantRole.MEMBER))
    );

    return this.getConversation(userId, conversation.id);
  }

  /**
   * The caller's conversation list, most recently active first.
   *
   * Keyset-paginated on `COALESCE(last_message_at, created_at)` — the same
   * expression the list is ordered by, so the cursor is exact. A keyset rather
   * than `OFFSET` because a thread's activity timestamp moves under a paging
   * client, which would make an offset paginator skip or repeat rows.
   *
   * Authorisation is structural: the join is on the caller's OWN participant row
   * (`left_at IS NULL`), so no predicate can widen the result set.
   */
  async listConversations(userId: string, query: ConversationQueryDto): Promise<ConversationPageResponseDto> {
    const limit = query.limit ?? 20;

    const idQuery = this.conversationsRepo
      .createQueryBuilder("c")
      .innerJoin(ConversationParticipant, "me", "me.conversation_id = c.id AND me.user_id = :userId", { userId })
      .where("me.left_at IS NULL")
      .andWhere("me.is_deleted = false")
      .andWhere("c.is_deleted = false")
      .select("c.id", "conversationId")
      .orderBy("COALESCE(c.last_message_at, c.created_at)", "DESC")
      .limit(limit + 1);

    if (query.before) idQuery.andWhere("COALESCE(c.last_message_at, c.created_at) < :before", { before: new Date(query.before) });
    if (query.type) idQuery.andWhere("c.type = :type", { type: query.type });

    const idRows = await idQuery.getRawMany<{ conversationId: string }>();
    const hasMore = idRows.length > limit;
    const ids = idRows.slice(0, limit).map((row) => row.conversationId);
    if (ids.length === 0) return { data: [], nextCursor: null, hasMore: false };

    const [conversations, memberships] = await Promise.all([
      this.conversationsRepo.find({ where: { id: In(ids), isDeleted: false } }),
      this.participantsRepo.find({ where: { conversationId: In(ids), leftAt: IsNull(), isDeleted: false } })
    ]);

    const conversationById = new Map(conversations.map((c) => [c.id, c]));
    const names = await this.resolveNames(memberships.map((m) => m.userId));
    const mine = new Map(memberships.filter((m) => m.userId === userId).map((m) => [m.conversationId, m]));

    const data = ids
      .map((id) => {
        const conversation = conversationById.get(id);
        const membership = mine.get(id);
        if (!conversation || !membership) return null;
        return this.toConversationResponseDto(
          conversation,
          membership,
          memberships.filter((m) => m.conversationId === id),
          names
        );
      })
      .filter((dto): dto is ConversationResponseDto => dto !== null);

    return { data, nextCursor: hasMore ? ((data[data.length - 1]?.lastMessageAt ?? data[data.length - 1]?.createdAt)?.toISOString() ?? null) : null, hasMore };
  }

  /**
   * One conversation with its participant roster, from the caller's point of
   * view. 404s for a non-member — see the class comment.
   */
  async getConversation(userId: string, conversationId: string): Promise<ConversationResponseDto> {
    const membership = await this.requireMembership(userId, conversationId);
    const conversation = await this.conversationsRepo.findOne({ where: { id: conversationId, isDeleted: false } });
    if (!conversation) throw new MessagingAccessException("not_a_participant");

    const roster = await this.participantsRepo.find({ where: { conversationId, leftAt: IsNull(), isDeleted: false } });
    const names = await this.resolveNames(roster.map((p) => p.userId));
    return this.toConversationResponseDto(conversation, membership, roster, names);
  }

  /** Adds members to a group thread. Idempotent per user. Moderator-only. */
  async addParticipants(actorId: string, conversationId: string, dto: AddParticipantsDto): Promise<ConversationResponseDto> {
    await this.requireModerator(actorId, conversationId);

    const conversation = await this.conversationsRepo.findOne({ where: { id: conversationId, isDeleted: false } });
    if (!conversation) throw new MessagingAccessException("not_a_participant");
    if (conversation.type !== ConversationType.GROUP) throw new BadRequestException("Participants can only be added to a group conversation");

    const active = await this.participantsRepo.find({ where: { conversationId, leftAt: IsNull(), isDeleted: false }, select: { userId: true } });
    const activeIds = new Set(active.map((p) => p.userId));
    const toAdd = [...new Set(dto.participantIds)].filter((id) => !activeIds.has(id));
    if (toAdd.length === 0) return this.getConversation(actorId, conversationId);

    if (active.length + toAdd.length > CONVERSATION_MAX_PARTICIPANTS) {
      throw new BadRequestException(`A conversation may have at most ${CONVERSATION_MAX_PARTICIPANTS} participants`);
    }

    const known = await this.usersRepo.find({ where: { id: In(toAdd), isDeleted: false }, select: { id: true } });
    if (known.length !== toAdd.length) throw new NotFoundException("One or more participants not found");

    await this.participantsRepo.save(toAdd.map((id) => this.newParticipant(conversationId, id, ConversationParticipantRole.MEMBER)));
    return this.getConversation(actorId, conversationId);
  }

  /**
   * Removes a participant — or lets one remove themselves.
   *
   * Removal stamps `leftAt` rather than deleting: a partial unique index on
   * `left_at IS NULL` still guarantees at most one active membership, while the
   * roster history survives for moderation. Re-inviting creates a fresh row.
   *
   * A moderator may remove anyone *except themselves* — leaving is a
   * self-service action, so a moderator who wants out just leaves.
   */
  async removeParticipant(actorId: string, conversationId: string, targetUserId: string): Promise<{ removed: boolean }> {
    await this.requireMembership(actorId, conversationId);
    if (actorId !== targetUserId) await this.requireModerator(actorId, conversationId);

    const membership = await this.participantsRepo.findOne({ where: { conversationId, userId: targetUserId, leftAt: IsNull(), isDeleted: false } });
    if (!membership) return { removed: false };

    membership.leftAt = new Date();
    membership.unreadCount = 0;
    await this.participantsRepo.save(membership);
    return { removed: true };
  }

  /**
   * Renames a thread (moderator-only) and/or mutes it (self-service).
   *
   * Muting is deliberately per participant, not per conversation: one person
   * silencing a noisy thread must not silence it for everyone else.
   */
  async updateConversation(actorId: string, conversationId: string, dto: UpdateConversationDto): Promise<ConversationResponseDto> {
    const membership = await this.requireMembership(actorId, conversationId);

    if (dto.title !== undefined) {
      if (dto.title.trim().length === 0) throw new BadRequestException("title cannot be empty");
      if (!CONVERSATION_MODERATOR_ROLES.includes(membership.role)) throw new ForbiddenException("Only an owner or admin can rename a conversation");

      const conversation = await this.conversationsRepo.findOne({ where: { id: conversationId, isDeleted: false } });
      if (!conversation) throw new MessagingAccessException("not_a_participant");
      conversation.title = dto.title.trim();
      await this.conversationsRepo.save(conversation);
    }

    if (dto.isMuted !== undefined) {
      membership.isMuted = dto.isMuted;
      await this.participantsRepo.save(membership);
    }

    return this.getConversation(actorId, conversationId);
  }

  // ─── Messages ─────────────────────────────────────────────────────────────

  /**
   * Persists a message and announces it.
   *
   * Authorisation, the message, the projections and the outbox row all commit
   * together (see the class comment). `duplicate: true` means
   * `clientMessageId` was already used in this conversation and nothing new was
   * written — the client should collapse its optimistic bubble onto the row it is
   * given, and no live frame is emitted.
   */
  async sendMessage(userId: string, conversationId: string, dto: SendMessageDto): Promise<SendMessageResponseDto> {
    const type = dto.type ?? MessageType.TEXT;
    const body = dto.body?.trim() ?? "";
    if (type === MessageType.TEXT && body.length === 0) throw new BadRequestException("body is required for a text message");
    if (type !== MessageType.TEXT && !dto.metadata) throw new BadRequestException("metadata is required for a non-text message");

    const senderName = await this.resolveName(userId);

    const outcome = await this.dataSource.transaction(async (manager) => {
      // Authorised INSIDE the transaction: a membership revoked between the
      // caller's check and the write must not let a message through.
      await this.requireMembership(userId, conversationId, manager);

      const existing = await this.findByClientMessageId(manager, userId, conversationId, dto.clientMessageId);
      if (existing) return { message: existing, duplicate: true };

      const draft = manager.create(Message, {
        conversationId,
        senderId: userId,
        type,
        body: type === MessageType.TEXT ? body : null,
        replyToId: dto.replyToId ?? null,
        clientMessageId: dto.clientMessageId,
        metadata: dto.metadata ?? null
      });

      let saved: Message;
      try {
        saved = await manager.save(draft);
      } catch (error) {
        // Two sockets from one client raced on the same clientMessageId. The
        // unique index is the authority; the loser re-reads the winner's row so
        // both callers see the same message instead of one getting a 500.
        if (!this.isUniqueViolation(error)) throw error;
        const raced = await this.findByClientMessageId(manager, userId, conversationId, dto.clientMessageId);
        if (!raced) throw error;
        return { message: raced, duplicate: true };
      }

      // The sender already has it on device.
      await manager
        .createQueryBuilder()
        .update(ConversationParticipant)
        .set({ lastDeliveredMessageId: saved.id, lastDeliveredAt: new Date() })
        .where("conversation_id = :conversationId", { conversationId })
        .andWhere("user_id = :userId", { userId })
        .andWhere("left_at IS NULL")
        .execute();

      // …which means every other active member has one more unread message.
      await manager
        .createQueryBuilder()
        .update(ConversationParticipant)
        .set({ unreadCount: () => '"unread_count" + 1' })
        .where("conversation_id = :conversationId", { conversationId })
        .andWhere("user_id <> :userId", { userId })
        .andWhere("left_at IS NULL")
        .execute();

      // Denormalised conversation-list projection: the inbox must never scan
      // `messages` to render a preview.
      await manager
        .createQueryBuilder()
        .update(Conversation)
        .set({ lastMessageId: saved.id, lastMessageAt: saved.createdAt, lastMessagePreview: body ? excerpt(body, 200) : type })
        .where("id = :conversationId", { conversationId })
        .execute();

      await this.publishMessageReceived(manager, saved, senderName);
      return { message: saved, duplicate: false };
    });

    const response = this.toMessageResponseDto(outcome.message, senderName);

    // Post-commit only. A rolled-back message must never reach a live socket.
    if (!outcome.duplicate) this.realtimeBus.publish({ conversationId, message: response });

    return { message: response, duplicate: outcome.duplicate };
  }

  /**
   * Message history, newest first, keyset-paginated on `createdAt`.
   *
   * A keyset cursor is the right call for a chat thread: a client paging back
   * through history must not have its window shift when a new message arrives,
   * which is precisely what happens in a live thread. `before` is the
   * `createdAt` of the oldest row on the previous page; `(createdAt, id)` is the
   * tiebreaker so two messages written in the same transaction cannot be split
   * across a page boundary.
   */
  async listMessages(userId: string, conversationId: string, query: MessageQueryDto): Promise<MessagePageResponseDto> {
    await this.requireMembership(userId, conversationId);

    const limit = query.limit ?? 30;
    const rows = await this.messagesRepo.find({
      where: {
        conversationId,
        isDeleted: false,
        ...(query.before ? { createdAt: LessThan(new Date(query.before)) } : {}),
        ...(query.type ? { type: query.type } : {})
      },
      order: { createdAt: "DESC", id: "DESC" },
      take: limit + 1
    });

    const hasMore = rows.length > limit;
    const page = rows.slice(0, limit);
    const names = await this.resolveNames(page.map((m) => m.senderId));

    return {
      data: page.map((m) => this.toMessageResponseDto(m, names.get(m.senderId) ?? null)),
      nextCursor: hasMore && page.length > 0 ? page[page.length - 1].createdAt.toISOString() : null,
      hasMore
    };
  }

  // ─── Read / delivery state ────────────────────────────────────────────────

  /**
   * Advances the caller's read high-water mark and recomputes their unread count
   * in ONE statement.
   *
   * Deriving the count from `last_read_at` instead of writing a literal 0 is what
   * makes the denormalised counter self-healing: any drift from a lost increment,
   * or a send that interleaved with this update, is corrected the next time the
   * user reads the thread. Setting the mark and the count in the same UPDATE also
   * means there is no instant where the mark has moved but the count has not.
   *
   * Omitting `lastReadMessageId` means "I have read everything currently in the
   * thread", which is what a client does on open — and which the derived count
   * handles naturally, since no message is newer than now.
   */
  async markRead(userId: string, conversationId: string, dto: UpdateReadStateDto): Promise<ReadStateResponseDto> {
    const membership = await this.requireMembership(userId, conversationId);

    let markId: string | null = null;
    let markAt = new Date();

    if (dto.lastReadMessageId) {
      const message = await this.messagesRepo.findOne({ where: { id: dto.lastReadMessageId, conversationId, isDeleted: false } });
      // A message id from a different conversation must not advance this one's
      // mark — otherwise any known message id would be a cross-thread write.
      if (!message) throw new NotFoundException("Message not found in this conversation");
      markId = message.id;
      markAt = message.createdAt;
    }

    const result = await this.participantsRepo
      .createQueryBuilder()
      .update(ConversationParticipant)
      .set({
        lastReadMessageId: markId,
        lastReadAt: markAt,
        readState: MessageDeliveryState.READ,
        unreadCount: () =>
          "(SELECT COUNT(*)::int FROM messages m WHERE m.conversation_id = conversation_participants.conversation_id AND m.sender_id <> conversation_participants.user_id AND m.created_at > :readMarkAt)"
      })
      .where("conversation_id = :conversationId", { conversationId })
      .andWhere("user_id = :userId", { userId })
      .andWhere("left_at IS NULL")
      .setParameter("readMarkAt", markAt.toISOString())
      .returning("unread_count")
      .execute();

    if (markId) await this.writeReceipts({ userId, conversationId, marker: { id: markId, createdAt: markAt }, kind: "read", since: membership.lastReadAt });

    return { conversationId, lastReadMessageId: markId, lastReadAt: markAt, unreadCount: readReturningInt(result, "unread_count") };
  }

  /**
   * Records that the caller has messages on device up to
   * `lastDeliveredMessageId`, writing one `message_receipts` row per message
   * sent by somebody else in the newly-covered range.
   *
   * The mark may only move forward: clients report state on every foreground and
   * on every reconnect, so an out-of-order report must not walk the high-water
   * mark backwards and re-report an older range.
   */
  async markDelivered(userId: string, conversationId: string, dto: UpdateDeliveryStateDto): Promise<DeliveryStateResponseDto> {
    const membership = await this.requireMembership(userId, conversationId);

    const marker = await this.messagesRepo.findOne({ where: { id: dto.lastDeliveredMessageId, conversationId, isDeleted: false } });
    if (!marker) throw new NotFoundException("Message not found in this conversation");

    if (membership.lastDeliveredMessageId) {
      const previous = await this.messagesRepo.findOne({ where: { id: membership.lastDeliveredMessageId, conversationId }, select: { createdAt: true } });
      if (previous && previous.createdAt.getTime() > marker.createdAt.getTime()) {
        return { conversationId, lastDeliveredMessageId: membership.lastDeliveredMessageId, lastDeliveredAt: membership.lastDeliveredAt, receiptsUpdated: 0 };
      }
    }

    const now = new Date();
    const receiptsUpdated = await this.writeReceipts({
      userId,
      conversationId,
      marker: { id: marker.id, createdAt: marker.createdAt },
      kind: "delivered",
      since: membership.lastDeliveredAt
    });

    await this.participantsRepo
      .createQueryBuilder()
      .update(ConversationParticipant)
      .set({ lastDeliveredMessageId: marker.id, lastDeliveredAt: now })
      .where("conversation_id = :conversationId", { conversationId })
      .andWhere("user_id = :userId", { userId })
      .andWhere("left_at IS NULL")
      .execute();

    return { conversationId, lastDeliveredMessageId: marker.id, lastDeliveredAt: now, receiptsUpdated };
  }

  /**
   * Read/delivered state per participant, for the sender's "seen by" ticks.
   *
   * Returns the *newest* state per user rather than every receipt row, so the
   * response stays bounded by the participant count.
   */
  async listReadReceipts(userId: string, conversationId: string): Promise<MessageReceiptStateDto[]> {
    await this.requireMembership(userId, conversationId);

    const others = await this.otherParticipantIds(userId, conversationId);
    if (others.length === 0) return [];

    const receipts = await this.receiptsRepo.find({ where: { conversationId, userId: In(others) }, order: { createdAt: "DESC" } });

    const byUser = new Map<string, MessageReceiptStateDto>();
    for (const receipt of receipts) {
      const existing = byUser.get(receipt.userId);
      if (!existing) {
        byUser.set(receipt.userId, { userId: receipt.userId, readAt: receipt.readAt, deliveredAt: receipt.deliveredAt });
        continue;
      }
      // Rows arrive newest-first, so the first non-null value per field wins.
      existing.readAt = existing.readAt ?? receipt.readAt;
      existing.deliveredAt = existing.deliveredAt ?? receipt.deliveredAt;
    }
    return [...byUser.values()];
  }

  // ─── Internals ────────────────────────────────────────────────────────────

  /**
   * Writes receipts for every message by another participant in the range
   * `(since, marker]`. Returns how many rows were actually inserted.
   *
   * Bounded below by the caller's previous mark, so the common case writes only
   * what arrived since the last report; bounded above by {@link RECEIPT_BATCH_LIMIT}
   * so a first-ever report on a very long thread cannot fan out unboundedly.
   *
   * A read implies a delivery, so a `read` report also fills `deliveredAt` when
   * it is still NULL — a client that went straight to "read" without reporting
   * delivery first must not leave a permanently undelivered receipt. The insert
   * is `ON CONFLICT DO NOTHING` against the unique `(message_id, user_id)` index,
   * because a reconnecting client re-reports the same state constantly and that
   * must be cheap rather than an error.
   */
  private async writeReceipts(args: {
    userId: string;
    conversationId: string;
    marker: { id: string; createdAt: Date };
    kind: "read" | "delivered";
    since: Date | null;
  }): Promise<number> {
    const { userId, conversationId, marker, kind, since } = args;

    const others = await this.otherParticipantIds(userId, conversationId);
    if (others.length === 0) return 0;

    // The covered window is always `(since, marker]`. Without a `since` it is
    // "everything up to the marker", which is the first-ever report.
    const candidates = await this.messagesRepo.find({
      where: [{ conversationId, senderId: In(others), isDeleted: false }, { createdAt: LessThanOrEqual(marker.createdAt) }, ...(since ? [{ createdAt: MoreThan(since) }] : [])],
      select: { id: true },
      order: { createdAt: "ASC" },
      take: RECEIPT_BATCH_LIMIT
    });
    if (candidates.length === 0) return 0;

    const now = new Date();
    const result = await this.receiptsRepo
      .createQueryBuilder()
      .insert()
      .into(MessageReceipt)
      .values(
        candidates.map((message) => ({
          messageId: message.id,
          conversationId,
          userId,
          // A read implies the message reached the device, so both columns are
          // stamped on a read report; `orIgnore` keeps a pre-existing row (with
          // its earlier, truthful timestamp) untouched.
          deliveredAt: now,
          readAt: kind === "read" ? now : null
        }))
      )
      .orIgnore()
      .execute();

    // Conflicts mean the receipt already existed — the normal case on reconnect.
    // Report only the rows actually written, which is what `raw` holds.
    return Array.isArray(result.raw) ? result.raw.length : 0;
  }

  /**
   * Announces a stored message to the notification pipeline.
   *
   * Published **in the caller's transaction** as a `message.received` event with
   * a `conversation_participants` audience. Resolving that audience lazily, at
   * handling time, means someone added to the thread between the send and the
   * job still hears about it — and the send transaction never pays for a
   * participant lookup, keeping it a single INSERT plus a couple of updates.
   *
   * The idempotency key is per message, so a retried send or a replayed event
   * can never produce a second notification.
   */
  private async publishMessageReceived(manager: EntityManager, message: Message, senderName: string | null): Promise<void> {
    const event: MessageReceivedEvent = {
      type: DomainEventType.MESSAGE_RECEIVED,
      occurredAt: message.createdAt,
      idempotencyKey: buildIdempotencyKey(DomainEventType.MESSAGE_RECEIVED, message.id),
      actorId: message.senderId,
      audience: { kind: "conversation_participants", conversationId: message.conversationId, excludeUserId: message.senderId },
      aggregate: { type: DomainAggregateType.MESSAGE, id: message.id },
      payload: {
        messageId: message.id,
        conversationId: message.conversationId,
        senderName,
        excerpt: message.body ? excerpt(message.body) : message.metadata ? "[attachment]" : ""
      }
    };
    await this.eventPublisher.publishInTransaction(manager, event);
  }

  private async findByClientMessageId(manager: EntityManager, senderId: string, conversationId: string, clientMessageId: string): Promise<Message | null> {
    return manager.getRepository(Message).findOne({ where: { conversationId, senderId, clientMessageId } });
  }

  private async otherParticipantIds(userId: string, conversationId: string): Promise<string[]> {
    const rows = await this.participantsRepo.find({ where: { conversationId, leftAt: IsNull(), isDeleted: false }, select: { userId: true } });
    return rows.map((r) => r.userId).filter((id) => id !== userId);
  }

  private newParticipant(conversationId: string, userId: string, role: ConversationParticipantRole): ConversationParticipant {
    return this.participantsRepo.create({
      conversationId,
      userId,
      role,
      isMuted: false,
      unreadCount: 0,
      readState: MessageDeliveryState.SENT,
      lastReadMessageId: null,
      lastReadAt: null,
      lastDeliveredMessageId: null,
      lastDeliveredAt: null,
      leftAt: null
    });
  }

  private async resolveName(userId: string): Promise<string | null> {
    const user = await this.usersRepo.findOne({ where: { id: userId }, select: { id: true, name: true } });
    return user?.name ?? null;
  }

  /** One batched lookup for a page of sender names, not one per message. */
  private async resolveNames(userIds: string[]): Promise<Map<string, string>> {
    const unique = [...new Set(userIds.filter(Boolean))].slice(0, NAME_BATCH_LIMIT);
    if (unique.length === 0) return new Map();
    const users = await this.usersRepo.find({ where: { id: In(unique) }, select: { id: true, name: true } });
    return new Map(users.map((u) => [u.id, u.name]));
  }

  private toMessageResponseDto(message: Message, senderName: string | null): MessageResponseDto {
    return {
      id: message.id,
      conversationId: message.conversationId,
      senderId: message.senderId,
      senderName,
      type: message.type,
      body: message.body,
      replyToId: message.replyToId,
      clientMessageId: message.clientMessageId,
      metadata: message.metadata,
      editedAt: message.editedAt,
      createdAt: message.createdAt
    };
  }

  private toConversationResponseDto(
    conversation: Conversation,
    mine: ConversationParticipant,
    roster: ConversationParticipant[],
    names: Map<string, string>
  ): ConversationResponseDto {
    return {
      id: conversation.id,
      type: conversation.type,
      title: conversation.title,
      participants: roster.map((p) => ({
        userId: p.userId,
        name: names.get(p.userId) ?? null,
        avatarUrl: null,
        role: p.role,
        unreadCount: p.unreadCount,
        lastReadAt: p.lastReadAt,
        lastDeliveredAt: p.lastDeliveredAt,
        joinedAt: p.joinedAt,
        isMuted: p.isMuted
      })),
      lastMessageId: conversation.lastMessageId,
      lastMessageAt: conversation.lastMessageAt,
      lastMessagePreview: conversation.lastMessagePreview,
      // The caller's own numbers, which are the only ones this view is about.
      unreadCount: mine.unreadCount,
      lastReadMessageId: mine.lastReadMessageId,
      lastReadAt: mine.lastReadAt,
      lastDeliveredMessageId: mine.lastDeliveredMessageId,
      readState: mine.readState,
      isMuted: mine.isMuted,
      createdAt: conversation.createdAt,
      updatedAt: conversation.updatedAt
    };
  }

  private isUniqueViolation(error: unknown): boolean {
    const e = error as { code?: string; driverError?: { code?: string } };
    return (e.driverError?.code ?? e.code) === "23505";
  }
}

export interface MessageReceiptStateDto {
  userId: string;
  readAt: Date | null;
  deliveredAt: Date | null;
}

/**
 * Canonical key for a one-to-one thread: the two user ids, sorted and joined.
 *
 * Sorting makes the key order-independent, so "A messages B" and "B messages A"
 * collide in the unique index instead of creating two threads for one pair.
 */
export function buildDirectKey(a: string, b: string): string {
  return [a, b].sort().join("|");
}

/** Reads an int out of a Postgres `RETURNING` clause, defaulting to 0. */
function readReturningInt(result: { raw?: unknown }, column: string): number {
  const row = Array.isArray(result.raw) ? (result.raw[0] as Record<string, unknown> | undefined) : undefined;
  const value = row?.[column];
  return typeof value === "number" ? value : Number(value ?? 0);
}
